"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { apiUrl, GALLERY_PATH, hostOf, sinceLabel, type GalleryApi } from "@/lib/api";

export default function GalleryPage() {
  const [apis, setApis] = useState<GalleryApi[] | null>(null);

  useEffect(() => {
    fetch(apiUrl(GALLERY_PATH))
      .then((r) => r.json())
      .then((b) => setApis(b.apis))
      .catch(() => setApis([]));
  }, []);

  return (
    <main className="mx-auto flex min-h-screen max-w-4xl flex-col px-4">
      <header className="flex items-center justify-between py-6">
        <Link href="/" className="flex items-center gap-2 text-ash hover:text-bone">
          <span className="text-pulse">✚</span>
          <span className="font-display font-semibold tracking-tight text-bone">LAZARUS</span>
        </Link>
        <Link href="/" className="rounded-lg bg-pulse px-3 py-1.5 text-sm font-bold text-void">
          Raise a new one →
        </Link>
      </header>

      <div className="mb-6">
        <h1 className="font-display text-3xl font-bold tracking-tight">Live APIs</h1>
        <p className="mt-1 text-sm text-ash">
          Every one was generated by the agent from a real page and refreshes on its own.
        </p>
      </div>

      {apis === null ? (
        <p className="text-ash">loading…</p>
      ) : apis.length === 0 ? (
        <div className="rounded-xl border border-line bg-panel/50 p-10 text-center">
          <p className="text-ash">No live APIs yet.</p>
          <Link href="/" className="mt-2 inline-block text-data hover:underline">
            Be the first — paste a URL →
          </Link>
        </div>
      ) : (
        <ul className="grid gap-3 pb-10 sm:grid-cols-2">
          {apis.map((a) => (
            <li
              key={a.slug}
              className="flex flex-col rounded-xl border border-line bg-panel/60 p-4 transition-colors hover:border-pulse/40"
            >
              <div className="flex items-center gap-2">
                <span className="h-2 w-2 rounded-full bg-pulse" />
                <span className="truncate font-display font-semibold text-bone">
                  {hostOf(a.source_url)}
                </span>
                <span className="ml-auto rounded border border-line px-1.5 py-0.5 text-[10px] uppercase tracking-widest text-ash">
                  {a.strategy === "json_xhr" ? "hidden API" : "html"}
                </span>
              </div>

              {a.description && (
                <p className="mt-2 line-clamp-2 text-sm text-ash">{a.description}</p>
              )}

              <div className="mt-3 flex items-center gap-3 text-xs text-ash">
                <span className="text-data">{a.record_count} records</span>
                <span>·</span>
                <span>refreshed {sinceLabel(a.last_refreshed)}</span>
              </div>

              <div className="mt-3 flex gap-2 border-t border-line pt-3 text-sm">
                <a
                  href={apiUrl(a.endpoint)}
                  target="_blank"
                  rel="noreferrer"
                  className="text-pulse hover:underline"
                >
                  GET {a.endpoint}
                </a>
                <a
                  href={apiUrl(a.docs)}
                  target="_blank"
                  rel="noreferrer"
                  className="ml-auto text-data hover:underline"
                >
                  docs →
                </a>
              </div>
            </li>
          ))}
        </ul>
      )}
    </main>
  );
}
